### ISSUE TITLE
another usage: convert after phpcs

### ISSUE THREAD

**Issue by sinkcup** [micheh/phpcs-gitlab#65]
now:

```
phpcs:
  script: vendor/bin/phpcs --report=full --report-\\Micheh\\PhpCodeSniffer\\Report\\Gitlab=phpcs-quality-report.json
  artifacts:
    reports:
      codequality: phpcs-quality-report.json
```

expect:

```
phpcs:
  script:
    - ./vendor/bin/phpcs --report=json --report-file=phpcs.json --standard=PSR12 src/
    - ./vendor/bin/phpcs-gitlab phpcs.json phpcs-quality-report.json
  artifacts:
    reports:
      codequality: phpcs-quality-report.json
```
